### ISSUE TITLE
repository structure

### ISSUE THREAD

**Issue by JanKoppe** [nuest/bagtainers#3]
I don't think versioning the containers by hand is a good idea. This quickly gets out of hand and makes clean versioning difficult (see #2 problems with travis).

A better solution would be to use git the way it's meant to be: version the containers with git releases or version branches.

**Comment by nuest** [comment]
The thing is that in this repo, I want all the different version to be there to be able to track how we got to the "standardized" version... but I see your point, I could also track that by looking at the history.

What do you think about..
- adding a tag `v1`, changing all occurences of "bagtainer version" to `1`.
- changing _all_ repositories to follow the structure "without /container directory" (this is work that I'd like to avoid... but might be worth it)

**Comment by JanKoppe** [comment]
I'm leaning towards GitFlow. This would solve the problem of parallel bagtainer development. Working Bagtainers, or "versions" we would like to save (as we do now with folders) would get released tagged as v0.x (e.g. 0005 → v0.5), leading up to our final standardized version of v1.0.

Changing _all_ repositories to the new folder structure would destroy the ability to track the evolution of bagtainers, thus should be avoided.

Switching to feature branches or tagged releases would make it possible to easily differentiate travis builds and define a simpler, atomic travis configuration that only focuses on this one version of a Bagtainer, instead of trying to cover every possible version we came up with.

**Comment by nuest** [comment]
The thing is that 0001 and 0002 are not _versions_ of bagtainers but have completely different contents. `0005` is the identifier of the bagtainer and has nothing to do with the version used in it.

**Comment by JanKoppe** [comment]
Aah, okay. In that case, the developed Bagtainer standard version should be applied to all different Bagtainers (0001 … ). Commits that change this version should then be tagged with v0.x.

But, this leads to the question: How much of the content of Bagtainers is really individual? Do we really need 10+ different example Bagtainers? iMO everything but the source data and the individual Bagtainer.yml should be included in the Bagtainer standard. Furthermore a repository split between Bagtainer standard and Bagtainer examples should be made.

Maybe I'm thinking too complicated or too far ahead, but the current structure seems very limited and not sustainable in the future.

**Comment by JanKoppe** [comment]
This Issue has been resolved verbally. We will continue with the current structure.
